//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18051
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiFiConnection.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiFiConnection.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ApplicationIcon {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 WFiConnection 的本地化字符串。
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序进入后台运行。 的本地化字符串。
        /// </summary>
        internal static string BackgroundRuningInfo {
            get {
                return ResourceManager.GetString("BackgroundRuningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消设定 的本地化字符串。
        /// </summary>
        internal static string CancelShutdown {
            get {
                return ResourceManager.GetString("CancelShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 设定关机 的本地化字符串。
        /// </summary>
        internal static string SetShutdown {
            get {
                return ResourceManager.GetString("SetShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已共享 的本地化字符串。
        /// </summary>
        internal static string Shared {
            get {
                return ResourceManager.GetString("Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ShareStarted {
            get {
                object obj = ResourceManager.GetObject("ShareStarted", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ShareStopped {
            get {
                object obj = ResourceManager.GetObject("ShareStopped", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 共享Wifi 的本地化字符串。
        /// </summary>
        internal static string ShareWifi {
            get {
                return ResourceManager.GetString("ShareWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WiFi共享已取消。 的本地化字符串。
        /// </summary>
        internal static string ShareWifiCancelInfo {
            get {
                return ResourceManager.GetString("ShareWifiCancelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共享WiFi失败。 的本地化字符串。
        /// </summary>
        internal static string ShareWififailedInfo {
            get {
                return ResourceManager.GetString("ShareWififailedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共享WiFi成功。 的本地化字符串。
        /// </summary>
        internal static string ShareWifiSuccessInfo {
            get {
                return ResourceManager.GetString("ShareWifiSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关机定时已取消。 的本地化字符串。
        /// </summary>
        internal static string ShutdownCancelInfo {
            get {
                return ResourceManager.GetString("ShutdownCancelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关机时间设定为： 的本地化字符串。
        /// </summary>
        internal static string ShutdownInfo {
            get {
                return ResourceManager.GetString("ShutdownInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设定关机时间 的本地化字符串。
        /// </summary>
        internal static string ShutdownTimerState {
            get {
                return ResourceManager.GetString("ShutdownTimerState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未共享 的本地化字符串。
        /// </summary>
        internal static string Unshared {
            get {
                return ResourceManager.GetString("Unshared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消共享 的本地化字符串。
        /// </summary>
        internal static string UnShareWifi {
            get {
                return ResourceManager.GetString("UnShareWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2.0更新说明：
        ///1、中文界面，界面美化
        ///2、定时关机功能的修复，设定后默认搭建时自动设定
        ///3、定时关机同步倒计时
        ///4、定时关机提示泡泡
        ///5、新增开机自启、软件启动时自动搭建功能
        ///
        ///v2.1更新说明：
        ///1、增加定时关机自动设定功能选项
        ///
        ///v3.0更新说明：
        ///1、增加WiFi分享功能，一键共享WiFi。
        ///
        ///Edited by hanyue(zhou chenghao)
        ///2013.12.26 的本地化字符串。
        /// </summary>
        internal static string UpdateInstruction {
            get {
                return ResourceManager.GetString("UpdateInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V3.0 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
